### ISSUE TITLE
Slow Mysql

### ISSUE THREAD

**Issue by dcnl1980** [shincoder/homestead-docker#24]
I'm using this docker on my mac for local developments, but the mysql in this container is very slow. How I can speed things up?

**Comment by jaouadk** [comment]
Mysql is not within the container, it's in a separate container that we don't manage directly ( see docker-compose.yml ).

Being slow can be related to your machine rather than the container itself, because it works fine for me and others.

You can also try the official mysql docker image https://github.com/docker-library/mysql
